# Explicit module import
import "cman"
import "cobbler"
import "debmirror"
import "dhcp"
import "dns"
import "httpd"
import "puppet"
import "rsync"
import "screen"
import "sysctl"
import "tftp"
import "xinetd"
